In [4]:
import numpy as np

In [6]:
k = 3
c = np.arange(k,0,-1)
c

array([3, 2, 1])

In [7]:
c = np.diag(c)
c

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 1]])

In [8]:
x = (-1) * np.ones((k,k),dtype='int')
x 

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [9]:
y = c+x
y

array([[ 2, -1, -1],
       [-1,  1, -1],
       [-1, -1,  0]])

In [10]:
z = y[:,0:k-1]
z

array([[ 2, -1],
       [-1,  1],
       [-1, -1]])

In [11]:
contrast_mat = np.tril(z,k=0)
contrast_mat

array([[ 2,  0],
       [-1,  1],
       [-1, -1]])

In [12]:
I = np.ones((1,3),dtype='int')
I

array([[1, 1, 1]])

In [ ]:
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.svd.html